### ISSUE TITLE
restfool.New() should accept public Config object

### ISSUE THREAD

**Issue by WalumNitdoof** [cseeger-epages/restfool-go#2]
**Problem**
Imagine you have a application who use yaml as configuration file format. That's why you cannot use restfool at this point.

**Solution**
Make config object public accessible and paste it as parameter to New().

**Result**
If a user has a different format he can convert it on his own into a restfool.Config object and paste it to New().

see this [PR](#3 )

**Comment by cseeger-epages** [comment]
not maintained anymore
